### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by ccoVeille** [essentialkaos/aligo#188]
I looked at readme and the screenshots, but I still don't understand what is the about, and so its purpose.

Please note, I'm not sarcastic or judging.

I noted the tool can display the struct alignement info in a visual way.

But I cannot figure why I need this, because I have no idea what is a struct alignment info.

I'm simply clueless after reading your README

from my little understanding after reading, I think your project could be about reporting whitespaces or indentation issue, but except if it's in the struct tags, gofmt or gofumpt would fix any issue.

I'm sure I'll figure it out by using the tool, or read at the code and tests. But it will require time to do it.

So here is my feedback, people reads README quickly, then look away, the README could be improved.

Something like what you tried to solve by providing this tool.

Something else that is interesting in a README is to list the "what this tool is not about"

Thanks

**Comment by andyone** [comment]
Hi! You can read about struct alignment [here](https://medium.com/@codewithkushal/understanding-struct-padding-in-go-in-depth-guide-ed70c0432c63).

**Comment by ccoVeille** [comment]
Thanks for the link it helped me a lot, so I opened #190 to suggest some README improvments.
